config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]

    end
end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    return unless user.present?

    can :create, Like
    can :create, Comment
    can :create, Post
    can :destroy, Post do |post|
      post.try(:user) == user
    end
    can :destroy, Comment do |comment|
      comment.try(:user) == user
    end
    can :destroy, Like do |like|
      like.try(:user) == user
    end
    can :update, Post do |post|
      post.try(:user) == user
    end
    can :update, Comment do |comment|
      comment.try(:user) == user
    end
    return unless user.admin?

    can :manage, :all
  end
  # Define abilities for the user here. For example:
  #
  #   return unless user.present?
  #   can :read, :all
  #   return unless user.admin?
  #   can :manage, :all
  #
  # The first argument to `can` is the action you are giving the user
  # permission to do.
  # If you pass :manage it will apply to every action. Other common actions
  # here are :read, :create, :update and :destroy.
  #
  # The second argument is the resource the user can perform the action on.
  # If you pass :all it will apply to every resource. Otherwise pass a Ruby
  # class of the resource.
  #
  # The third argument is an optional hash of conditions to further filter the
  # objects.
  # For example, here the user can only update published articles.
  #
  #   can :update, Article, published: true
  #
  # See the wiki for details:
  # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'post_id'

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comment
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(
      author_id: current_user.id,
      post_id: @post.id,
      text: comment_params
    )

    @comment.save if @comment.valid?
    redirect_to user_post_path(current_user, @post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)[:text]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])

    @like = current_user.likes.new(
      author_id: current_user.id,
      post_id: @post.id
    )

    if @like.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # @user =User.includes(posts:[:comments]).find(params[:user_id])

    @user = User.find(params[:user_id])
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes([:author])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params[:id])
    respond_to do |format|
      format.html do
        if @post.save
          redirect_to user_post_path(current_user, @post), notice: 'Post was successfully created.'
          # redirect_to '/users/#{@post_new.user_id}/posts', messaage: 'Post was successfully created.'
        else
          render :new, status: 'Error: Post was not created.'
        end
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MYBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <script src="https://kit.fontawesome.com/b331332bf9.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

app/views/posts/_add_comment.html.erb
<div>
  <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/comments", scope: :comment do |format| %>
    <div>
       <%= format.label :Enter_Comment %><br>
       <%= format.text_area :text, rows: 10, require: true %>
       <%= format.submit "Comment" %>
    </div>
    <% end %>
</div>

app/views/posts/index.html.erb
<h1>Here is a lists of a given user</h1>
<section>
   <div class= "container">
      <div class="user-img">
          <img src="<%= @user.photo %>" alt="<%= @user.name %>">
        </div>
      <div class="details">
        <h1 class="user-head"><%= @user.name %></h1>
        <p class="user-para">Number of posts: <%= @user.posts_counter || 0 %></p>
   </div>
  <% @user.recent_posts.each do |post| %>
    <%= link_to user_post_path(@user, post) do %>
      <h2>Post: <%= post.id %></h2>
      <% end %>
      <div class= "container">
        <div class="details">
          <h1 class="user-head"><%= post.title %></h1>
          <p>post description: <span><%= post.text%></span> </p>
          <p class="user-para">Number of comments: <%= post.comments_counter || 0 %></p>
          <p class="user-para">Number of likes: <%= post.likes_counter || 0 %></p>
        </div>
   </div>
    <ul>
      <% post.recent_comment.each do |rec| %>
      <li><%= rec.author.name %>:<%= rec.text %></li>
       <% end %>
    </ul>
  <% end %>
  <button>pagination</button>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post, url:  user_posts_path, method: :post, local: true do |f| %>
<div>
  <%= f.label :Post_title, require: true %><br>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :Enter_Text %><br>
  <%= f.text_area :text, rows: 10, require: true %>  
</div>
<% @post.errors.full_messages_for(:title).each do |message| %>
  <div><%= message %></div>
<% end %>
<div>
  <%= f.submit "Create Post" %>
</div>

<% end %>

app/views/posts/show.html.erb
<h1>Here is a lists of a given post</h1>
<section>
  <div class= "container">
        <div class="details">
          <h1 class="user-head"><%= @post.title %></h1>
          <p>post deescription: <span><%= @post.text%></span> </p>
          <p class="user-para">Number of comments: <%= @post.comments_counter || 0 %></p>
          <p class="user-para">Number of likes: <%= @post.likes_counter || 0 %></p>
        </div>
      </div>
      <div class="recent-comments">
     <div>
        <%= form_with url: "/users/#{@post.author_id}/posts/#{@post.id}/likes", scope: :like do |f| %>
        <%= f.submit "Like" %>
        <% end %>
      </div> 
      
      <ul>
      <% @comments.each do |rec| %>
      <li><%= rec.author.name %> : <%= rec.text %></li>
       <% end %>
      </ul>

      <%= render "add_comment" %>
  </div>
</section>

app/views/users/index.html.erb
<h1>Here is a lists of a given user</h1>

<section>
  <% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
      <div class= "container">
        <div class="user-img">
          <img src="<%= user.photo %>">
        </div>
        <div class="details">
          <h1 class="user-head"><%= user.name %></h1>
          <p class="user-para">Number of posts: <%= user.posts_counter || 0 %></p>
        </div>
      </div>
      
        <li><%= link_to 'Show', user %></li>
      <% end %>
  <% end %>
</section>

app/views/users/show.html.erb
<h1>Here is a lists of a given user</h1>
<section>
    <div class= "container-fluid">
        <div class="user-img">
          <img src="<%= @user.photo %>" alt="<%= @user.name %>">
        </div>
        <div class="details">
          <h1 class="user-head"><%= @user.name %></h1>
          <p class="user-para">Number of posts: <%= @user.posts_counter || 0 %></p>
    </div>
        <div class="user-bio">
        <h3>Bio: </h3>
        <p><%= @user.bio %></p>
        </div>
      </div>
      <div class="user-post">
       <% @user.recent_posts.each do |post| %>
       <%= link_to user_post_path(@user, post.id) do %>
        <div class="post-container">
         <h2>Post: <%= post.title %></h2>
         <p><%= post.text %></p>
         <div class="counter">
                  <span>comments:<%= post.comments_counter || 0 %></span>
                  <span>likes:<%= post.likes_counter || 0 %></span>
         </div>
        </div>
       <% end %>
       <% end %>
       <button class="btn btn-primary"> <%= link_to "See all posts", user_posts_path(@user) %></button>
      </div>
</section>